### ISSUE TITLE
Fix Formatting pushes changes automatically

### ISSUE THREAD

**Issue by DavidGarciaCat** [carlosV2/bash-dev-tools#8]
Hey there,

Have found this issue working with the `ff` command. It seems have fixed (just 1) issue on `src/` and has pushed all changes automatically, instead of ask me if I want to do it. This is the output:

```
➜  crowd2fund git:(<branch-name>) ff
Fixing SRC files... fixed
Fixing FEATURE files... clean
Fixing SPEC files... clean
askQuestion:read:10: -p: no coprocess
Commit created
askQuestion:read:10: -p: no coprocess
Commit pushed to code repository
➜  crowd2fund git:(<branch-name>)
```

Best,

**Comment by carlosV2** [comment]
Are you using the latest version?
Which is your OS?
Which is you bash version?

**Comment by DavidGarciaCat** [comment]
Yes, I am using the latest version. In fact, this weekend have reinstalled the entire OS, so I have cloned the last release. However, I have noted the same issue before to reinstall the OS.

My OS is Mac OS X 10.11 "El Capitan" (please note this OS is `GM Candidate`).

I use [Oh My Zsh](http://ohmyz.sh/), also installed just a couple of days ago.

**Comment by carlosV2** [comment]
If you are using `El Capitan`, then I guess your bash version is `3.2.57(1)`. Please, can you run `bash --version` and post it? Thanks.

**Comment by DavidGarciaCat** [comment]
Here you are:

```
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin15)
Copyright (C) 2007 Free Software Foundation, Inc.
```

**Comment by carlosV2** [comment]
Oh My Zsh is providing a builtin command for `read` with their very own interface. That's why those questions (and any other potential question) will not work on your shell. This project is supporting `bash` exclusively (that's why the name is `bash-dev-tools`).

Please, feel free to look for a solution for your shell and send it to me so we can plan how to create a shared base code for both (or more) shells.

Sorry.

**Comment by DavidGarciaCat** [comment]
:+1: Will review that, as commented. Thanks!
